logging:
  level:
    root: info

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    table: SCHEMA_HISTORY
    locations:
      - classpath:/db/migration
      - classpath:/db/migration-data